-- public.kosdaq_live definition

-- Drop table

-- DROP TABLE public.kosdaq_live;

CREATE TABLE public.kosdaq_live (
	"name" text NOT NULL,
	description text NULL,
	logoid text NULL,
	update_mode text NULL,
	"type" text NULL,
	"close" numeric NULL,
	pricescale numeric NULL,
	minmov numeric NULL,
	fractional text NULL,
	minmove2 numeric NULL,
	currency text NULL,
	"change" numeric NULL,
	volume numeric NOT NULL,
	relative_volume_10d_calc numeric NULL,
	market_cap_basic numeric NULL,
	fundamental_currency_code text NULL,
	price_earnings_ttm numeric NULL,
	earnings_per_share_diluted_ttm numeric NULL,
	earnings_per_share_diluted_yoy_growth_ttm numeric NULL,
	dividends_yield_current numeric NULL,
	sector_tr text NULL,
	market text NULL,
	sector text NULL,
	recommendation_mark numeric NULL,
	exchange text NULL,
	perf_w numeric NULL,
	perf_1_m numeric NULL,
	perf_3_m numeric NULL,
	perf_6_m numeric NULL,
	perf_y_t_d numeric NULL,
	perf_y numeric NULL,
	perf_5_y numeric NULL,
	perf_10_y numeric NULL,
	perf_all numeric NULL,
	volatility_w numeric NULL,
	volatility_m numeric NULL,
	premarket_close numeric NULL,
	premarket_change numeric NULL,
	premarket_gap numeric NULL,
	premarket_volume numeric NULL,
	gap numeric NULL,
	volume_change numeric NULL,
	postmarket_close numeric NULL,
	postmarket_change numeric NULL,
	postmarket_volume numeric NULL,
	perf_1_y_market_cap numeric NULL,
	price_earnings_growth_ttm numeric NULL,
	price_sales_current numeric NULL,
	price_book_fq numeric NULL,
	price_to_cash_f_operating_activities_ttm numeric NULL,
	price_free_cash_flow_ttm numeric NULL,
	price_to_cash_ratio numeric NULL,
	enterprise_value_current numeric NULL,
	enterprise_value_to_revenue_ttm numeric NULL,
	enterprise_value_to_ebit_ttm numeric NULL,
	enterprise_value_ebitda_ttm numeric NULL,
	dps_common_stock_prim_issue_fy numeric NULL,
	dps_common_stock_prim_issue_fq numeric NULL,
	dividends_yield numeric NULL,
	dividend_payout_ratio_ttm numeric NULL,
	dps_common_stock_prim_issue_yoy_growth_fy numeric NULL,
	continuous_dividend_payout numeric NULL,
	continuous_dividend_growth numeric NULL,
	gross_margin_ttm numeric NULL,
	operating_margin_ttm numeric NULL,
	pre_tax_margin_ttm numeric NULL,
	net_margin_ttm numeric NULL,
	free_cash_flow_margin_ttm numeric NULL,
	return_on_assets_fq numeric NULL,
	return_on_equity_fq numeric NULL,
	return_on_invested_capital_fq numeric NULL,
	research_and_dev_ratio_ttm numeric NULL,
	sell_gen_admin_exp_other_ratio_ttm numeric NULL,
	total_assets_fq numeric NULL,
	total_current_assets_fq numeric NULL,
	cash_n_short_term_invest_fq numeric NULL,
	total_liabilities_fq numeric NULL,
	total_debt_fq numeric NULL,
	net_debt_fq numeric NULL,
	total_equity_fq numeric NULL,
	current_ratio_fq numeric NULL,
	quick_ratio_fq numeric NULL,
	debt_to_equity_fq numeric NULL,
	cash_n_short_term_invest_to_total_debt_fq numeric NULL,
	cash_f_operating_activities_ttm numeric NULL,
	cash_f_investing_activities_ttm numeric NULL,
	cash_f_financing_activities_ttm numeric NULL,
	free_cash_flow_ttm numeric NULL,
	capital_expenditures_ttm numeric NULL,
	recommend_all numeric NULL,
	recommend_m_a numeric NULL,
	recommend_other numeric NULL,
	r_s_i numeric NULL,
	mom numeric NULL,
	a_o numeric NULL,
	c_c_i20 numeric NULL,
	stoch_k numeric NULL,
	stoch_d numeric NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	CONSTRAINT kosdaq_live_pkey PRIMARY KEY (name, volume, created_at)
);
CREATE INDEX kosdaq_live_sector_idx ON public.kosdaq_live USING btree (sector);

-- all_예측 h1, h2, h3, h4, h5, h6, ~ h23

ALTER TABLE kosdaq_live
ADD COLUMN full_model_1h_prediction NUMERIC,
ADD COLUMN full_model_2h_prediction NUMERIC,
ADD COLUMN full_model_3h_prediction NUMERIC,
ADD COLUMN full_model_4h_prediction NUMERIC,
ADD COLUMN full_model_5h_prediction NUMERIC,
ADD COLUMN full_model_6h_prediction NUMERIC,
ADD COLUMN full_model_7h_prediction NUMERIC,
ADD COLUMN full_model_8h_prediction NUMERIC,
ADD COLUMN full_model_9h_prediction NUMERIC,
ADD COLUMN full_model_10h_prediction NUMERIC,
ADD COLUMN full_model_11h_prediction NUMERIC,
ADD COLUMN full_model_12h_prediction NUMERIC,
ADD COLUMN full_model_13h_prediction NUMERIC,
ADD COLUMN full_model_14h_prediction NUMERIC,
ADD COLUMN full_model_15h_prediction NUMERIC,
ADD COLUMN full_model_16h_prediction NUMERIC,
ADD COLUMN full_model_17h_prediction NUMERIC,
ADD COLUMN full_model_18h_prediction NUMERIC,
ADD COLUMN full_model_19h_prediction NUMERIC,
ADD COLUMN full_model_20h_prediction NUMERIC,
ADD COLUMN full_model_21h_prediction NUMERIC,
ADD COLUMN full_model_22h_prediction NUMERIC,
ADD COLUMN full_model_23h_prediction NUMERIC,
ADD COLUMN market_model_1h_prediction NUMERIC,
ADD COLUMN market_model_2h_prediction NUMERIC,
ADD COLUMN market_model_3h_prediction NUMERIC,
ADD COLUMN market_model_4h_prediction NUMERIC,
ADD COLUMN market_model_5h_prediction NUMERIC,
ADD COLUMN market_model_6h_prediction NUMERIC,
ADD COLUMN market_model_7h_prediction NUMERIC,
ADD COLUMN market_model_8h_prediction NUMERIC,
ADD COLUMN market_model_9h_prediction NUMERIC,
ADD COLUMN market_model_10h_prediction NUMERIC,
ADD COLUMN market_model_11h_prediction NUMERIC,
ADD COLUMN market_model_12h_prediction NUMERIC,
ADD COLUMN market_model_13h_prediction NUMERIC,
ADD COLUMN market_model_14h_prediction NUMERIC,
ADD COLUMN market_model_15h_prediction NUMERIC,
ADD COLUMN market_model_16h_prediction NUMERIC,
ADD COLUMN market_model_17h_prediction NUMERIC,
ADD COLUMN market_model_18h_prediction NUMERIC,
ADD COLUMN market_model_19h_prediction NUMERIC,
ADD COLUMN market_model_20h_prediction NUMERIC,
ADD COLUMN market_model_21h_prediction NUMERIC,
ADD COLUMN market_model_22h_prediction NUMERIC,
ADD COLUMN market_model_23h_prediction NUMERIC,
ADD COLUMN sector_model_1h_prediction NUMERIC,
ADD COLUMN sector_model_2h_prediction NUMERIC,
ADD COLUMN sector_model_3h_prediction NUMERIC,
ADD COLUMN sector_model_4h_prediction NUMERIC,
ADD COLUMN sector_model_5h_prediction NUMERIC,
ADD COLUMN sector_model_6h_prediction NUMERIC,
ADD COLUMN sector_model_7h_prediction NUMERIC,
ADD COLUMN sector_model_8h_prediction NUMERIC,
ADD COLUMN sector_model_9h_prediction NUMERIC,
ADD COLUMN sector_model_10h_prediction NUMERIC,
ADD COLUMN sector_model_11h_prediction NUMERIC,
ADD COLUMN sector_model_12h_prediction NUMERIC,
ADD COLUMN sector_model_13h_prediction NUMERIC,
ADD COLUMN sector_model_14h_prediction NUMERIC,
ADD COLUMN sector_model_15h_prediction NUMERIC,
ADD COLUMN sector_model_16h_prediction NUMERIC,
ADD COLUMN sector_model_17h_prediction NUMERIC,
ADD COLUMN sector_model_18h_prediction NUMERIC,
ADD COLUMN sector_model_19h_prediction NUMERIC,
ADD COLUMN sector_model_20h_prediction NUMERIC,
ADD COLUMN sector_model_21h_prediction NUMERIC,
ADD COLUMN sector_model_22h_prediction NUMERIC,
ADD COLUMN sector_model_23h_prediction NUMERIC;